from comm_interface.ml_comm import CommInterface, Actions
import time

comm: CommInterface = CommInterface()
comm.connect()

# comm.communicate_test(10000)
# comm.send_action(Actions.END)
# comm.close_comm()
# print("Finished!")

while True:
    time.sleep(1)
    comm.send_action(Actions.RUN)
    time.sleep(3.6)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.45)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.583)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(2.067)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.45)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.483)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(4.719)
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.417)
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.35)
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.316)
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.384)
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.35)
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(2.216)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.4)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.717)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.95)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.417)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.7)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(4.414)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.419)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.816)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(3.434)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.433)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.383)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.85)
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.7)
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.367)
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.975)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.433)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.767)
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(1.036)
    comm.send_action(Actions.STOP)
    time.sleep(1)
    # break
