from comm_interface.ml_comm import CommInterface, Actions
import time

# comm: CommInterface = CommInterface(0)
# comm.connect()
# comm.communicate_test(50000)
# comm.send_action(Actions.END)
# comm.close_comm()
# print("Finished!")

comm: CommInterface = CommInterface()
comm.connect()

adjust: float = -0.0200

while True:
    time.sleep(1)
    # for i in range(1000):
    #     comm.distance_from_center()
    #     time.sleep(1)
    comm.send_action(Actions.RUN)
    time.sleep(3.58333 + adjust)
    # print(comm.distance_from_center())
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.43333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.56633 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(2.05033 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.43333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.46333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(4.70233 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.40033 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.33333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.29933 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.36733 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.33333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(2.19933 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.38333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.70333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.93333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.40033 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.68333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(4.39733 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.40233 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.78933 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(3.42533 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.41633 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.36633 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.83333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.68333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.350333 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_LEFT)
    time.sleep(0.95833 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.41633 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(0.75033 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.TURN_RIGHT)
    time.sleep(1.02033 + adjust)
    print(comm.is_oriented())
    print(comm.distance_from_center())
    comm.send_action(Actions.STOP)
    time.sleep(1)
    # break
